# Generated by Django 3.1.7 on 2023-01-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230109_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='instructions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
