# Generated by Django 3.1.7 on 2023-01-18 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_comment_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment',
        ),
    ]
