# Generated by Django 3.1.7 on 2023-01-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userimage_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='fileType',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
